version: '3'
services:
    rails.test:
        build:
            context: .
            dockerfile: train/runtimes/app/Dockerfile
            args:
                - USER_NAME='${USER_NAME}'
                - NODESOURCE_VERSION='${NODESOURCE_VERSION}'
        image: train/app
        ports:
            - 3000:3000
            - 1234:1234
            - 26162:26162
        volumes:
            - '.:/var/www/html'
            - rbenv:/root/.rbenv
        networks:
            - train
        depends_on:
            - mysql
        tty: true
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - train
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - train
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
        ports:
            - 8080:80
        volumes:
            - phpmyadmin:/sessions
        networks:
           - train
        depends_on:
            - mysql
networks:
    train:
        driver: bridge
volumes:
    rbenv:
        driver: local
    mysql:
        driver: local
    phpmyadmin:
        driver: local